'use client'
import { useEffect, useState, useMemo } from 'react'
import { createClient } from '@/lib/supabase/client'
import { MaintenanceLog, MaintenanceStatus } from '@/types'
import { useAuth } from '@/hooks/useAuth'
import { getStatusColor, formatDateShort } from '@/lib/utils'
import Modal from '@/components/ui/Modal'
import MaintenanceForm from '@/components/MaintenanceForm'
import Badge from '@/components/ui/Badge'
import StatCard from '@/components/ui/StatCard'
import EmptyState from '@/components/ui/EmptyState'
import toast from 'react-hot-toast'
import { HiOutlinePlusCircle, HiOutlinePencilSquare, HiOutlineTrash, HiOutlineMagnifyingGlass, HiOutlineWrenchScrewdriver, HiOutlineClock, HiOutlineCheckCircle, HiOutlineExclamationTriangle } from 'react-icons/hi2'

export const dynamic = 'force-dynamic'
export default function MaintenancePage() {
  const [logs, setLogs] = useState<MaintenanceLog[]>([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [filterStatus, setFilter] = useState<MaintenanceStatus | 'all'>('all')
  const [addModal, setAddModal] = useState(false); const [editModal, setEditModal] = useState<{ open: boolean; log: MaintenanceLog | null }>({ open: false, log: null }); const [delModal, setDelModal] = useState<{ open: boolean; log: MaintenanceLog | null }>({ open: false, log: null }); const [formLoading, setFormLoad] = useState(false)
  const { isAdmin, isHR, profile } = useAuth(); const supabase = createClient()
  useEffect(() => { load() }, [])
  async function load() { setLoading(true); const { data, error } = await supabase.from('maintenance_logs').select('*').order('created_at', { ascending: false }); if (error) toast.error('Failed'); else setLogs(data || []); setLoading(false) }
  const stats = useMemo(() => ({ total: logs.length, pending: logs.filter(l => l.status === 'pending').length, ongoing: logs.filter(l => l.status === 'ongoing').length, completed: logs.filter(l => l.status === 'completed').length }), [logs])
  const filtered = useMemo(() => logs.filter(l => { const q = search.toLowerCase(); return (!q || l.asset_id.toLowerCase().includes(q) || l.issue.toLowerCase().includes(q) || l.technician.toLowerCase().includes(q)) && (filterStatus === 'all' || l.status === filterStatus) }), [logs, search, filterStatus])

  async function handleAdd(data: any) { setFormLoad(true); try { const { error } = await supabase.from('maintenance_logs').insert({ asset_id: data.asset_id, issue: data.issue, action_taken: data.action_taken || null, status: data.status, date_reported: data.date_reported, date_resolved: data.date_resolved || null, technician: data.technician, created_by: profile?.id }); if (error) throw error; if (data.status !== 'completed') await supabase.from('assets').update({ status: 'repair' }).eq('asset_id', data.asset_id); toast.success('Record added'); setAddModal(false); load() } catch (e: any) { toast.error(e.message) } finally { setFormLoad(false) } }
  async function handleEdit(data: any) { if (!editModal.log) return; setFormLoad(true); try { const { error } = await supabase.from('maintenance_logs').update({ issue: data.issue, action_taken: data.action_taken || null, status: data.status, date_reported: data.date_reported, date_resolved: data.date_resolved || null, technician: data.technician }).eq('id', editModal.log.id); if (error) throw error; if (data.status === 'completed') await supabase.from('assets').update({ status: 'available' }).eq('asset_id', data.asset_id); toast.success('Updated'); setEditModal({ open: false, log: null }); load() } catch (e: any) { toast.error(e.message) } finally { setFormLoad(false) } }
  async function handleDelete() { if (!delModal.log) return; try { const { error } = await supabase.from('maintenance_logs').delete().eq('id', delModal.log.id); if (error) throw error; toast.success('Deleted'); setDelModal({ open: false, log: null }); load() } catch (e: any) { toast.error(e.message) } }

  const th: React.CSSProperties = { textAlign: 'left', padding: '12px 16px', fontSize: 11, fontWeight: 800, color: '#fff', opacity: 0.5, textTransform: 'uppercase', letterSpacing: '0.08em', borderBottom: '1px solid var(--table-border)', background: 'var(--table-header-bg)' }
  const td: React.CSSProperties = { padding: '12px 16px', fontSize: 13, borderBottom: '1px solid var(--table-border-light)', color: '#fff' }
  const filterInp: React.CSSProperties = { padding: '9px 12px', background: 'var(--bg-input)', border: '1px solid var(--glass-border)', borderRadius: 10, color: '#fff', fontSize: 13, outline: 'none', fontFamily: "'Plus Jakarta Sans',sans-serif", colorScheme: 'dark' }
  const card: React.CSSProperties = { background: 'var(--bg-card)', backdropFilter: 'blur(10px) saturate(180%)', border: '1px solid var(--glass-border)', borderRadius: 14, overflow: 'hidden' }

  if (loading) return (<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 240 }}><div style={{ width: 20, height: 20, border: '2px solid rgba(0,112,243,0.3)', borderTopColor: '#0070f3', borderRadius: '50%', animation: 'spin 0.7s linear infinite' }} /></div>)

  return (
    <div className="animate-fadeIn" style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', flexWrap: 'wrap', gap: 12 }}><div><p style={{ fontSize: 10, fontWeight: 700, color: '#0070f3', textTransform: 'uppercase', letterSpacing: '0.15em', marginBottom: 4 }}>Service</p><h1 style={{ fontSize: 28, fontWeight: 800, color: '#fff', margin: 0, letterSpacing: '-0.02em' }}>Maintenance</h1><p style={{ fontSize: 13, color: 'var(--text-muted)', marginTop: 4 }}>Track and manage repair records</p></div>{isAdmin && <button onClick={() => setAddModal(true)} className="btn-primary"><HiOutlinePlusCircle size={15} /> Add Record</button>}</div>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 14 }}><StatCard title="Total" value={stats.total} icon={<HiOutlineWrenchScrewdriver size={20} style={{ color: '#0070f3' }} />} iconBg="rgba(0,112,243,0.12)" /><StatCard title="Pending" value={stats.pending} icon={<HiOutlineClock size={20} style={{ color: '#fbbf24' }} />} iconBg="rgba(251,191,36,0.12)" /><StatCard title="Ongoing" value={stats.ongoing} icon={<HiOutlineExclamationTriangle size={20} style={{ color: '#fb923c' }} />} iconBg="rgba(251,146,60,0.12)" /><StatCard title="Completed" value={stats.completed} icon={<HiOutlineCheckCircle size={20} style={{ color: '#34d399' }} />} iconBg="rgba(52,211,153,0.12)" /></div>
      <div className="glass" style={{ padding: 14, display: 'flex', gap: 10, flexWrap: 'wrap' }}><div style={{ flex: 1, minWidth: 200, position: 'relative' }}><HiOutlineMagnifyingGlass style={{ position: 'absolute', left: 11, top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)', width: 15, height: 15 }} /><input id="search-maint" name="search" type="text" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} style={{ ...filterInp, width: '100%', paddingLeft: 34, boxSizing: 'border-box' as any }} /></div><select id="filter-maint" name="filter_status" value={filterStatus} onChange={e => setFilter(e.target.value as any)} style={{ ...filterInp, cursor: 'pointer' }}><option value="all">All Status</option><option value="pending">Pending</option><option value="ongoing">Ongoing</option><option value="completed">Completed</option></select></div>

      {filtered.length === 0 ? (<div style={card}><EmptyState title="No records" description="No maintenance records found" icon={<HiOutlineWrenchScrewdriver style={{ width: 24, height: 24, color: 'var(--text-muted)' }} />} /></div>) : (
        <div style={card}><div style={{ overflowX: 'auto' }}><table style={{ width: '100%', borderCollapse: 'collapse' }}><thead><tr><th style={th}>Asset</th><th style={th}>Issue</th><th style={th}>Status</th><th style={th}>Technician</th><th style={th}>Reported</th><th style={th}>Resolved</th><th style={{ ...th, textAlign: 'right' }}>Actions</th></tr></thead><tbody>
          {filtered.map(log => (<tr key={log.id} className="table-row" style={{ transition: 'background 0.15s' }}><td style={td}><span style={{ fontFamily: 'monospace', fontWeight: 700, color: '#0070f3', fontSize: 13 }}>{log.asset_id}</span></td><td style={{ ...td, color: 'var(--text-secondary)', maxWidth: 200 }}><span style={{ display: 'block', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{log.issue}</span></td><td style={td}><Badge className={getStatusColor(log.status)}>{log.status}</Badge></td><td style={{ ...td, color: 'var(--text-secondary)' }}>{log.technician}</td><td style={{ ...td, color: 'var(--text-muted)' }}>{formatDateShort(log.date_reported)}</td><td style={{ ...td, color: 'var(--text-muted)' }}>{log.date_resolved ? formatDateShort(log.date_resolved) : '—'}</td><td style={{ ...td, textAlign: 'right' }}><div style={{ display: 'flex', gap: 3, justifyContent: 'flex-end' }}><button onClick={() => setEditModal({ open: true, log })} style={{ padding: 6, borderRadius: 8, color: '#0070f3', background: 'none', border: 'none', cursor: 'pointer', display: 'inline-flex', transition: 'background 0.15s' }} onMouseEnter={e => (e.currentTarget.style.background = 'rgba(0,112,243,0.1)')} onMouseLeave={e => (e.currentTarget.style.background = 'none')}><HiOutlinePencilSquare size={16} /></button>{(isAdmin || isHR) && <button onClick={() => setDelModal({ open: true, log })} style={{ padding: 6, borderRadius: 8, color: 'var(--danger-light)', background: 'none', border: 'none', cursor: 'pointer', display: 'inline-flex', transition: 'background 0.15s' }} onMouseEnter={e => (e.currentTarget.style.background = 'var(--danger-bg)')} onMouseLeave={e => (e.currentTarget.style.background = 'none')}><HiOutlineTrash size={16} /></button>}</div></td></tr>))}
        </tbody></table></div></div>
      )}

      <Modal isOpen={addModal} onClose={() => setAddModal(false)} title="New Maintenance Record"><MaintenanceForm onSubmit={handleAdd} onCancel={() => setAddModal(false)} isLoading={formLoading} /></Modal>
      <Modal isOpen={editModal.open} onClose={() => setEditModal({ open: false, log: null })} title="Edit Record">{editModal.log && <MaintenanceForm initialData={{ asset_id: editModal.log.asset_id, issue: editModal.log.issue, action_taken: editModal.log.action_taken || '', status: editModal.log.status, date_reported: editModal.log.date_reported, date_resolved: editModal.log.date_resolved || '', technician: editModal.log.technician }} onSubmit={handleEdit} onCancel={() => setEditModal({ open: false, log: null })} isEdit isLoading={formLoading} />}</Modal>
      <Modal isOpen={delModal.open} onClose={() => setDelModal({ open: false, log: null })} title="Delete Record" compact><div style={{ textAlign: 'center', padding: '4px 0' }}><div style={{ width: 48, height: 48, borderRadius: 12, background: 'var(--danger-bg)', border: '1px solid var(--danger-border)', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 14px' }}><HiOutlineTrash style={{ width: 20, height: 20, color: 'var(--danger-light)' }} /></div><h3 style={{ fontSize: 15, fontWeight: 700, color: '#fff', margin: '0 0 6px' }}>Delete Record?</h3><p style={{ fontSize: 13, color: 'var(--text-muted)', margin: 0 }}>This cannot be undone.</p><div style={{ display: 'flex', justifyContent: 'center', gap: 8, marginTop: 16 }}><button onClick={() => setDelModal({ open: false, log: null })} className="btn-ghost">Cancel</button><button onClick={handleDelete} className="btn-danger">Delete</button></div></div></Modal>
    </div>
  )
}